Fixes
lifecycle-project/ds-helper pull request #117
Opened 2022-05-09 14:53 UTC by timcadman

I had previously mixed up a branch for fixes and a branch for new functions. I have separated off the fixes into their own branch.

2022-05-10 08:28 UTC, sidohaakma requested changes

2022-05-10 08:28 UTC, sidohaakma commented on NAMESPACE
> +importFrom(dsBaseClient,ds.meanSdGp)
Is this part of dsBase 6.2.0?

2022-05-12 12:29 UTC, timcadman commented on NAMESPACE
> +importFrom(dsBaseClient,ds.meanSdGp)
Nope that's part of 6.1

2022-05-17 04:33 UTC, sidohaakma approved these changes

2022-05-17 04:33 UTC, merged