Added as default to use all opals
lifecycle-project/ds-helper pull request #13
Opened 2020-08-19 07:24 UTC by timcadman

2020-08-19 13:18 UTC, sidohaakma requested changes

2020-08-19 13:18 UTC, sidohaakma commented on R/make-outcome.R
> +  print(data_available)
Why use print here?

2020-08-19 13:34 UTC, timcadman commented on R/make-outcome.R
> +  print(data_available)
If I use "message" it doesn't print the tibble, instead it prints, e.g. "c(var_name_1, var_name_2). I think there's something about tibbles that mean you need to use "print". If I'm getting this wrong though do say.

2020-08-25 07:13 UTC, sidohaakma commented on R/make-outcome.R
> +  print(data_available)
I think you can use print in the message context. Something like this message(print(tibbleobject)).

2020-09-03 19:49 UTC, sidohaakma approved these changes
I am going to merge it as is. I could not find a solution to not print the overhead in the message()

2020-09-03 19:49 UTC, merged