Maintenance
lifecycle-project/ds-helper pull request #39
Opened 2021-03-19 10:27 UTC by timcadman

> prerequisites:
> - install.packages("devtools")
> - install.packages("styler")
> - install.packages("pkgdown")

#### In general:

* [ ] Did you test the code against `https://armadillo.test.molgenis.org`?
* [ ] Have you ran `styler:::style_active_pkg()` to style the code-files
* [ ] Have you ran `devtools::check()` to be sure documentation is rerendered and code is quality checked?

#### Vignettes:

1. [ ] Did you create an .orig file and add it to the pre-render.R file?
2. [ ] Did you run the the pre-render.R file to regenerate the vignettes
3. [ ] Did you run `pkgdown::build_site()` to preview the documentation

2021-03-23 07:51 UTC, sidohaakma requested changes
Hi Tim, looks really nice. Keep the functions short approximately 300 lines is standard and always describe them even if they are internal functions. That way when you look at it later on you will know what it does. Use the @noRd annotation to

2021-03-23 07:51 UTC, sidohaakma commented on R/meta-manual.R
> +dh.metaManual <- function(fit, method = "ML"){
Is this an exported function? Anyway you need to describe it and use the @noRd annotation for internal functions.

2021-03-23 07:51 UTC, sidohaakma commented on R/pred-poly.R
> +dh.predPoly <- function(df, fixed, core_agevar, coeftab, conns, type = c("linear", "nonlinear")) {
Same here

2021-03-23 07:51 UTC, sidohaakma commented on R/mean-by-occasion.R
> +dh.meanByOccasion <- function(df, agevar, outcome, bands, conns, grouping = NULL) {
Is this an exported function? Anyway you need to describe it and use the @nord annotation for internal functions.

2021-03-23 07:51 UTC, sidohaakma commented on R/make-lmer-form.R
> +dh.makeLmerForm <- function(
Is this an exported function? Anyway you need to describe it and use the @nord annotation for internal functions.

2021-03-23 07:51 UTC, sidohaakma commented on R/make-age-polys.R
> +dh.makeAgePolys <- function(df, agevars, conns) {
Is this an exported function? Anyway you need to describe it and use the @nord annotation for internal functions.

2021-03-23 07:51 UTC, sidohaakma commented on R/lmer-tab.R
> +dh.lmerTab <- function(fit, coh, coh_format = "cols") {
Is this an exported function? Anyway you need to describe it and use the @nord annotation for internal functions.

2021-03-24 17:28 UTC, timcadman commented on R/meta-manual.R
> +dh.metaManual <- function(fit, method = "ML"){
Exported as function

2021-03-24 17:28 UTC, timcadman commented on R/pred-poly.R
> +dh.predPoly <- function(df, fixed, core_agevar, coeftab, conns, type = c("linear", "nonlinear")) {
Exported as function

2021-03-24 17:28 UTC, timcadman commented on R/mean-by-occasion.R
> +dh.meanByOccasion <- function(df, agevar, outcome, bands, conns, grouping = NULL) {
Exported as function

2021-03-24 17:28 UTC, timcadman commented on R/make-lmer-form.R
> +dh.makeLmerForm <- function(
Exported as function

2021-03-24 17:29 UTC, timcadman commented on R/make-age-polys.R
> +dh.makeAgePolys <- function(df, agevars, conns) {
Exported as function

2021-03-24 17:29 UTC, timcadman commented on R/lmer-tab.R
> +dh.lmerTab <- function(fit, coh, coh_format = "cols") {
Exported as function

2021-03-25 11:02 UTC, sidohaakma requested changes
You need to style the package. Indentation is wrong at some points. Check the checklist ;-D.

2021-03-25 11:03 UTC, sidohaakma commented
@timcadman you need to pull from the master as well, to resolve the conflicts.

2021-03-25 17:35 UTC, sidohaakma approved these changes

2021-03-25 17:35 UTC, merged