Newgetstats
lifecycle-project/ds-helper pull request #59
Opened 2021-08-12 13:15 UTC by timcadman

> prerequisites:
> - install.packages("devtools")
> - install.packages("styler")
> - install.packages("pkgdown")

#### In general:

* [ ] Did you test the code against `https://armadillo.test.molgenis.org`?
* [ ] Have you ran `styler:::style_active_pkg()` to style the code-files
* [ ] Have you ran `devtools::check()` to be sure documentation is rerendered and code is quality checked?

#### Vignettes:

1. [ ] Did you create an .orig file and add it to the pre-render.R file?
2. [ ] Did you run the the pre-render.R file to regenerate the vignettes
3. [ ] Did you run `pkgdown::build_site()` to preview the documentation

2021-08-12 13:17 UTC, timcadman commented
Hmm not sure how all of these other commits have ended up on this branch!! Still trying to get to grips with git :D

2021-08-12 13:23 UTC, timcadman commented
Ah ok, now I've merged the other branch its caught up :)

2021-09-21 09:55 UTC, sidohaakma requested changes
Run the styler and the check function!

2021-09-21 09:55 UTC, sidohaakma commented on R/lm-tab.R
> +
Please run the styler ;-D.

2021-09-30 21:11 UTC, sidohaakma commented on R/lm-tab.R
> +
styler::style_package(). You can ignore the check function then

2021-10-01 08:54 UTC, timcadman commented
Ok I think ive fixed it all now - can you review and approve?

2021-10-01 09:28 UTC, sidohaakma approved these changes

2021-10-01 09:28 UTC, merged